name: Use Kube-score

on:
    push:
      branches:
        - main

jobs:
  kube-score:
    runs-on: ubuntu-latest
    steps:
      - name: kube-score check
      # You may pin to the exact commit or the version.
      # uses: piraces/kube-score-ga@0eb83dcf2274cf7018257df01feb5d2f43f7cb59
        uses: piraces/kube-score-ga@v0.1.3
        with:
        # kube-score version to use
          kube-score-version: piraces/kube-score-ga@v0.1.3
        # Array of relative paths to execute kube-score with (separated with commas). It is mandatory to establish a wildcard for the files or the concrete filename.
          manifests-folders:  '../charts/grafana/*.yml'
        # Ignore exit code from kube-score and continue on error (for information purposes only)
          ignore-exit-code: 'true'
        # Generate an output file with the results of kube-score analysis for each manifest file (instead of printing in the standard output). Each analysis is separated by a text block.
          output-file: 'result.txt' 
